Repository scala/community-build, pull requests merged in 2020-11, with the labels that each got.

#1274 Newer 2.12 SHA, unbreaking scala-rewrites
  nightly.properties
  report/Report.scala
Labels: contents

#1277 add cats-parse
  community.conf
  dependencies.txt
  proj/cats-parse.conf
  projs.conf
Labels: contents

#1276 sbt 1.4.2 (was 1.4.1)
  advance
  community.conf
  narrow
  report/project/build.properties
Labels: contents

#1278 move to newer scalameta + scalafmt + scalapb + zinc
  community.conf
  dependencies.txt
  proj/sbt-collections.conf
  proj/sbt-core-macros.conf
  proj/sbt-util-cache.conf
  proj/sbt-util-control.conf
  proj/sbt-util-logging.conf
  proj/sbt-util-position.conf
  proj/sbt-util-relation.conf
  proj/sbt-util-tracking.conf
  proj/sbt-util.conf
  proj/scala-parallel-collections.conf
  proj/scalafmt.conf
  proj/scalameta.conf
  proj/scalapb.conf
  proj/shaded-jawn-parser.conf
  proj/zinc.conf
  projs.conf
  scripts/jobs/integrate/community-build
Labels: contents

#1281 CB 2.12 fixes
  nightly.properties
  proj/mdoc.conf
  proj/scalafix.conf
  report/Report.scala
Labels: contents

#1285 move to ScalaCheck 1.15
  proj/breeze.conf
  proj/scalacheck.conf
Labels: contents

#1282 2.11: advance project SHAs
  proj/airframe.conf
  proj/akka.conf
  proj/claimant.conf
  proj/data-class.conf
  proj/genjavadoc.conf
  proj/kind-projector.conf
  proj/log4s.conf
  proj/munit.conf
  proj/nscala-time.conf
  proj/scala-collection-compat.conf
  proj/scala-java8-compat.conf
  proj/scalameta.conf
  proj/scalaprops.conf
  proj/sconfig.conf
  proj/singleton-ops.conf
  proj/verify.conf
Labels: contents

#1286 new Scala 2.13 SHA
  nightly.properties
Labels: contents: Scala SHA

#1287 2.12: new Scala SHA
  nightly.properties
Labels: contents: Scala SHA

#1289 2.13: unfork playframework
  proj/playframework.conf
Labels: contents: other

#1291 unfreeze mercator
  proj/mercator.conf
Labels: contents: other

#1292 2.13: new Scala SHA
  nightly.properties
Labels: contents: Scala SHA

#1295 2.13: new Scala SHA
  nightly.properties
Labels: contents: Scala SHA

#1294 2.12: new Scala SHA
  nightly.properties
Labels: contents: Scala SHA

#1296 2.11: sbt 1.4.3
  advance
  community.conf
  narrow
  report/project/build.properties
Labels: contents: sbt version

#1297 2.12: sbt 1.4.3
  advance
  community.conf
  narrow
  report/project/build.properties
Labels: contents: sbt version

#1298 2.13: sbt 1.4.3
  advance
  community.conf
  narrow
  report/project/build.properties
Labels: contents: sbt version

#1299 2.13: new Scala SHA (2.13.4 candidate)
  nightly.properties
Labels: contents: Scala SHA

#1300 2.12: new Scala SHA
  nightly.properties
  proj/mima.conf
  proj/scala-parser-combinators.conf
  proj/scala-refactoring.conf
  proj/scalafix.conf
  proj/scalatest.conf
  proj/scoverage.conf
Labels: contents: Scala SHA

#1302 2.11: advance project SHAs
  proj/airframe.conf
  proj/claimant.conf
  proj/data-class.conf
  proj/genjavadoc.conf
  proj/implicitbox.conf
  proj/kind-projector.conf
  proj/munit.conf
  proj/nscala-time.conf
  proj/scala-collection-compat.conf
  proj/scala-hedgehog.conf
  proj/scala-java8-compat.conf
  proj/scala-typed-holes.conf
  proj/scalaprops.conf
  proj/scalatest.conf
  proj/sconfig.conf
  proj/singleton-ops.conf
  proj/spray-json.conf
  proj/verify.conf
Labels: contents: all project SHAs

#1303 2.12: advance project SHAs
  proj/airframe.conf
  proj/breeze.conf
  proj/claimant.conf
  proj/data-class.conf
  proj/genjavadoc.conf
  proj/implicitbox.conf
  proj/kind-projector.conf
  proj/mercator.conf
  proj/mima.conf
  proj/munit.conf
  proj/nscala-time.conf
  proj/scala-collection-compat.conf
  proj/scala-hedgehog.conf
  proj/scala-java8-compat.conf
  proj/scala-sculpt.conf
  proj/scala-typed-holes.conf
  proj/scalaprops.conf
  proj/sconfig.conf
  proj/shapeless-java-records.conf
  proj/singleton-ops.conf
  proj/spray-json.conf
  proj/ssl-config.conf
  proj/verify.conf
Labels: contents: all project SHAs

#1305 unfork twirl
  proj/twirl.conf
Labels: contents: other

#1306 2.13: new Scala SHA
  nightly.properties
  proj/genjavadoc.conf
Labels: contents: Scala SHA

#1307 add weaver-test (+ monix-bio + monix-catnap)
  community.conf
  dependencies.txt
  proj/monix-bio.conf
  proj/monix.conf
  proj/weaver-test.conf
  projs.conf
Labels: contents: other
